apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.component }}
  namespace: {{ .Release.Namespace}} 
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.com/health-checks: "true"
spec:
  tls:
  - hosts:
    - "mosip.{{ .Values.domain}}"
    secretName: selfsigned-cert-tls
  rules:
  - host: "mosip.{{ .Values.domain}}"
    http:
      paths:
      - path: /websub
        backend:
          serviceName: {{ .Values.services.serviceName }}
          servicePort: 80 

