apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  annotations:
     kubernetes.io/ingress.class: "nginx"
     cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    # nginx.com/health-checks: "true"
spec:
  rules:
  - host: "mosip.{{ .Values.domain}}"
    http:
      paths:
      - path: /registration-client
        backend:
          serviceName: {{ .Values.serviceName }}
          servicePort: 80 
  tls:
  - hosts:
    - "mosip.{{ .Values.domain}}"
    secretName: mosip-certificate
