apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: Route for application's https service.
  labels:
    application: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  host: "config.{{ .Values.domain}}"
  port:
    targetPort: {{ .Values.docker.containerPort }}
  #tls:
  #  termination: passthrough
  to:
    kind: Service
    name: {{ .Values.name }}
