apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.component }}
  namespace: {{ .Release.Namespace}} 
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.com/health-checks: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  rules:
  - host: "mosip.{{ .Values.domain}}"
    http:
      paths:
      - path: /config
        backend:
          serviceName: {{ .Values.name }} 
          servicePort: 80 
  tls:
  - hosts:
    - "mosip.{{ .Values.domain}}"
    secretName: letsencrypt-staging-certificate
