# Ansible script get container log file sizes of all the nodes.  The script
# runs 'du -mL /var/log/containers' command on each node.
- hosts: mzcluster, dmzcluster
  gather_facts: false
  tasks:
    - name: Get container file size
      shell: 'du -bL /var/log/containers/'
      register: size
      become: yes
      ignore_errors: yes

    - debug:
        msg: ' {{inventory_hostname}}:    {{size.stdout.split()[0]}}'
      ignore_errors: yes

#    - name: Get container file size
#      shell: 'du -bcL /var/log/containers/*regproc*'
#      register: size
#      become: yes
#      ignore_errors: yes
#
#    - debug:
#        #msg: ' {{inventory_hostname}}:  {{size.stdout.split()[0]}}'
#        msg: ' {{inventory_hostname}}:  {{size.stdout.split("\n")}}'
#      ignore_errors: yes
#
#    - name: Get container file size
#      shell: 'du -bcL /var/log/containers/*idrepo*'
#      register: size
#      become: yes
#      ignore_errors: yes
#
#    - debug:
#        #msg: ' {{inventory_hostname}}:  {{size.stdout.split()[0]}}'
#        msg: ' {{inventory_hostname}}:  {{size.stdout.split("\n")}}'
#      ignore_errors: yes

