apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: Route for application's https service.
  labels:
    application: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  host: "activemq.{{ .Values.domain}}"
  port:
    targetPort: {{ .Values.docker.webPort }}
  #tls:
  #  termination: passthrough
  to:
    kind: Service
    name: {{ .Values.name }}

