apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  rules:
  - host: "mosip.{{ .Values.domain}}"
    http:
      paths:
      - path: /activemq/admin
        backend:
          serviceName: {{ .Values.name }}
          servicePort: {{ .Values.docker.webPort }}
  tls:
  - hosts:
    - "mosip.{{ .Values.domain}}"
    secretName: letsencrypt-staging-certificate