apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: Route for application's https service.
  labels:
    application: {{ template "minio.fullname" . }}
  name: minio
  namespace: {{ .Release.Namespace }}
spec:
  host: "activemq.{{ .Values.domain}}"
  port:
    targetPort: {{ .Values.service.port }}
  #tls:
  #  termination: passthrough
  to:
    kind: Service
    name: {{ template "minio.fullname" . }}

