---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.volumeName }} 
spec:
  storageClassName: {{ .Values.sc.name }} 
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  selector:
    matchLabels:
      name: {{ .Values.persistence.volumeName }} 
