apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: Route for application's https service.
  labels:
    application: {{ .Values.component }}
  name: {{ .Values.component }}
spec:
  host: "packetmanager.apps.ocp.rnpdev.shop"
  port:
    targetPort: {{ .Values.services.containerPort }}
  #tls:
  #  termination: passthrough
  to:
    kind: Service
    name: {{ .Values.services.packet.serviceName }}
