- name: Install psql12 rpm
  yum: 
    name:  https://download.postgresql.org/pub/repos/yum/12/redhat/rhel-8-x86_64/pgdg-redhat-repo-42.0-11.noarch.rpm 
    state: present
  become: yes

- name: Install psql12
  yum:
    name:  postgresql12
    state: present
  become: yes

